export interface MapPoint {
  id: string;
  title: string;
  description: string;
  emoji: string;
  latitude: number;
  longitude: number;
}

export const mapPoints: MapPoint[] = [
  {
    id: '1',
    title: 'Coffee Shop',
    description: 'Best coffee in town! ☕',
    emoji: '☕',
    latitude: -37.8136,
    longitude: 144.9631,
  },
  {
    id: '2',
    title: 'Bubble Tea Place',
    description: 'Amazing bubble tea here! 🧋',
    emoji: '🧋',
    latitude: -37.7950,
    longitude: 144.9500,
  },
  {
    id: '3',
    title: 'Tea House',
    description: 'Beautiful tea house for relaxation 🫖',
    emoji: '🫖',
    latitude: -37.8300,
    longitude: 144.9800,
  },
  {
    id: '4',
    title: 'Coffee & Tea',
    description: 'Great coffee and tea selection ☕',
    emoji: '☕',
    latitude: -37.8150,
    longitude: 144.9650,
  },
  {
    id: '5',
    title: 'Bubble Tea Bar',
    description: '24/7 bubble tea bar 🧋',
    emoji: '🧋',
    latitude: -37.8000,
    longitude: 144.9750,
  },
  {
    id: '6',
    title: 'Tea Garden',
    description: 'Quiet tea garden space 🫖',
    emoji: '🫖',
    latitude: -37.8250,
    longitude: 144.9450,
  },
  {
    id: '7',
    title: 'Coffee Corner',
    description: 'Latest coffee trends here ☕',
    emoji: '☕',
    latitude: -37.8100,
    longitude: 144.9550,
  },
  {
    id: '8',
    title: 'Tea & Coffee',
    description: 'Fine tea and coffee experience 🫖',
    emoji: '🫖',
    latitude: -37.8200,
    longitude: 144.9700,
  },
  {
    id: '9',
    title: 'Coffee Bank',
    description: 'Coffee and banking services ☕',
    emoji: '☕',
    latitude: -37.8050,
    longitude: 144.9600,
  },
  {
    id: '10',
    title: 'Tea Hospital',
    description: 'Tea for health and wellness 🫖',
    emoji: '🫖',
    latitude: -37.8350,
    longitude: 144.9650,
  },
  {
    id: '11',
    title: 'Bubble Tea Station',
    description: 'Bubble tea and convenience 🧋',
    emoji: '🧋',
    latitude: -37.7900,
    longitude: 144.9400,
  },
  {
    id: '12',
    title: 'Coffee School',
    description: 'Learn about coffee ☕',
    emoji: '☕',
    latitude: -37.8400,
    longitude: 144.9750,
  },
  {
    id: '13',
    title: 'Tea Beach',
    description: 'Tea with beautiful beach views 🫖',
    emoji: '🫖',
    latitude: -37.8450,
    longitude: 144.9850,
  },
  {
    id: '14',
    title: 'Coffee Museum',
    description: 'Coffee art and history ☕',
    emoji: '☕',
    latitude: -37.8000,
    longitude: 144.9350,
  },
  {
    id: '15',
    title: 'Bubble Tea Stadium',
    description: 'Bubble tea sports venue 🧋',
    emoji: '🧋',
    latitude: -37.8500,
    longitude: 144.9700,
  },
  {
    id: '16',
    title: 'Coffee Airport',
    description: 'Coffee at the airport ☕',
    emoji: '☕',
    latitude: -37.8600,
    longitude: 144.9900,
  },
  {
    id: '17',
    title: 'Tea Station',
    description: 'Tea at the train station 🫖',
    emoji: '🫖',
    latitude: -37.7850,
    longitude: 144.9450,
  },
  {
    id: '18',
    title: 'Coffee Hotel',
    description: 'Luxury coffee accommodation ☕',
    emoji: '☕',
    latitude: -37.8550,
    longitude: 144.9550,
  },
  {
    id: '19',
    title: 'Bubble Tea Pharmacy',
    description: 'Bubble tea for health 🧋',
    emoji: '🧋',
    latitude: -37.7950,
    longitude: 144.9700,
  },
  {
    id: '20',
    title: 'Tea Post Office',
    description: 'Tea and mail services 🫖',
    emoji: '🫖',
    latitude: -37.8250,
    longitude: 144.9500,
  },
]; 